export const currencies = [
  { name: "Euro", symbol: "€", conversionRate: 0.91 },
  { name: "British Pound", symbol: "£", conversionRate: 0.75 },
  { name: "Japanese Yen", symbol: "¥", conversionRate: 110.52 },
  { name: "Australian Dollar", symbol: "A$", conversionRate: 1.37 },
  { name: "Canadian Dollar", symbol: "C$", conversionRate: 1.32 },
  { name: "Swiss Franc", symbol: "CHF", conversionRate: 0.92 },
  { name: "Chinese Yuan", symbol: "¥", conversionRate: 6.47 },
  { name: "Indian Rupee", symbol: "₹", conversionRate: 73.05 },
  { name: "Brazilian Real", symbol: "R$", conversionRate: 5.52 },
  { name: "South Korean Won", symbol: "₩", conversionRate: 1174.5 },
  { name: "Mexican Peso", symbol: "MXN$", conversionRate: 20.1 },
  { name: "Russian Ruble", symbol: "₽", conversionRate: 76.15 },
  { name: "Hong Kong Dollar", symbol: "HK$", conversionRate: 7.78 },
  { name: "Singapore Dollar", symbol: "S$", conversionRate: 1.36 },
  { name: "New Zealand Dollar", symbol: "NZ$", conversionRate: 1.49 },
  { name: "Swedish Krona", symbol: "kr", conversionRate: 8.77 },
  { name: "Norwegian Krone", symbol: "kr", conversionRate: 9.08 },
  { name: "Turkish Lira", symbol: "₺", conversionRate: 13.17 },
  { name: "South African Rand", symbol: "R", conversionRate: 15.27 },
  { name: "Emirati Dirham", symbol: "د.إ", conversionRate: 3.67 },
  { name: "Thai Baht", symbol: "฿", conversionRate: 32.75 },
  { name: "Thai Baht", symbol: "฿", conversionRate: 32.75 },
  { name: "Indonesian Rupiah", symbol: "Rp", conversionRate: 14153.5 },
  { name: "Vietnamese Dong", symbol: "₫", conversionRate: 23047 },
  { name: "Malaysian Ringgit", symbol: "RM", conversionRate: 4.17 },
  { name: "Philippine Peso", symbol: "₱", conversionRate: 51.33 },
  { name: "Taiwanese Dollar", symbol: "NT$", conversionRate: 28.8 },
  { name: "Bangladeshi Taka", symbol: "৳", conversionRate: 84.3 },
  { name: "Sri Lankan Rupee", symbol: "Rs", conversionRate: 202.5 },
  { name: "Pakistani Rupee", symbol: "₨", conversionRate: 176.25 },
  { name: "Cambodian Riel", symbol: "៛", conversionRate: 4100 },
];
